module PdfSolidConversion
  # Native SDK result code constants.
  module ErrorCode
    SUCCESS = 0
    CANCEL = 1
    FILE = 2
    PDF_PASSWORD = 3
    PDF_PAGE = 4
    PDF_FORMAT = 5
    PDF_SECURITY = 6
    OUT_OF_MEMORY = 7
    IO = 8
    COMPRESS = 9
    LICENSE_INVALID = 20
    LICENSE_EXPIRE = 21
    LICENSE_UNSUPPORTED_PLATFORM = 22
    LICENSE_UNSUPPORTED_ID = 23
    LICENSE_UNSUPPORTED_DEVICE = 24
    LICENSE_PERMISSION_DENY = 25
    LICENSE_UNINITIALIZED = 26
    LICENSE_ILLEGAL_ACCESS = 27
    LICENSE_FILE_READ_FAILED = 28
    LICENSE_OCR_PERMISSION_DENY = 29
    NO_TABLE = 40
    OCR_FAILURE = 41
    CONVERTING = 60
    INVALID_ARG = 80
    INVALID_HANDLE = 81
    MODEL_INVALID_FORMAT = 82
    MODEL_FUNCTION_UNSUPPORTED = 83
    MODEL_FORMAT_UNSUPPORTED = 84
    MODEL_SDK_MISMATCH = 85
    IMAGE_DATA_EMPTY = 86
    IMAGE_WH_ERROR = 87
    IMAGE_UNSUPPORTED_FORMAT = 88
    IMAGE_INVALID = 89
    EXPIRE = 90
    MISSING_ARG = 91
    LICENSE_UNSUPPORTED_API = 92
    LICENSE_MISMATCH = 93
    INVALID_TABLE = 94
    UNKNOWN = 100
  end
end